#!/bin/bash
#PBS -l nodes=1:ppn=12,walltime=00:1:10
#PBS -q batch
#PBS -N run
#PBS -j oe
#PBS -V

#cat $PBS_NODEFILE
cd ~/FinalProject/BubbleSort/serial
export OMP_NUM_THREADS=3
mpiexec -np 1 --map-by ppr:1:node --hostfile $PBS_NODEFILE ./BubbleSort.cx

